---

  # test_file is name of the data yaml file
  # the initating loop can be found in 
  # the playbook iterating over all data files
  # look for MAIN: EXECUTE ALL TESTS task
  - name: "TASKS: TESTING BEGINNING"
    set_fact:
      # path = tests/vlans/test_01/data.yml
      feature: "{{ test_file.path.split('/')[1] }}"
      test_name: "{{ test_file.path.split('/')[2] }}"
      data_file: "{{ test_file.path }}"

  - name: "{{ feature | upper }}: {{ test_name | upper }}-> LOAD DATA"
    include_vars:
      file: "{{ data_file }}"

  - name: "{{ feature | upper }}: {{ test_name | upper }}-> SET PATH"
    set_fact:
      test_path: "{{ output_dir }}/{{ feature }}/{{ test_name }}"

  - name: "{{ feature | upper }}: {{ test_name | upper }}-> CREATE DIRECTORY STRUCTURE"
    file:
      path: "{{ test_path }}"
      state: "directory"

  - name: "{{ feature | upper }}: {{ test_name | upper }}-> GENERATE {{ feature | upper }} CONFIG"
    template:
      src: "{{ lookup('first_found', file_paths) }}"
      dest: "./{{ test_path }}/generated_config.cfg"
    vars:
      file_paths:
        files: "{{ feature }}.j2"
        paths:
          - "{{ test_dir }}/{{ feature }}/{{ test_name }}"
          - "{{ template_dir }}/{{ meta['vendor'] }}/{{ meta['os'] }}/{{ meta.get('platform') }}/{{ meta.get('family') }}/{{ meta.get('model') }}"
          - "{{ template_dir }}/{{ meta['vendor'] }}/{{ meta['os'] }}/{{ meta.get('platform') }}/{{ meta.get('family') }}/defaults"
          - "{{ template_dir }}/{{ meta['vendor'] }}/{{ meta['os'] }}/{{ meta.get('platform') }}/defaults"
          - "{{ template_dir }}/{{ meta['vendor'] }}/{{ meta['os'] }}/defaults"
          - "{{ template_dir }}/{{ meta['vendor'] }}/defaults"
          - "./"
    ignore_errors: true
    register: "template_status"

  - name: "{{ feature | upper }}: {{ test_name | upper }}-> COMPARE EXPECTED TO TEST RESULTS"
    ntc_differ:
      pre_change: "{{ test_dir }}/{{ feature }}/{{ test_name }}/expected_config.cfg"
      post_change: "{{ test_path }}/generated_config.cfg"
      dest: "./{{ test_path }}/test_results.cfg"
    register: "diff"
    when: "template_status['changed']"

  - name: "{{ feature | upper }}: {{ test_name | upper }}-> TEMPLATE FAILURE TO TEST RESULTS"
    copy:
      content: "{{ template_status['msg'] }}"
      dest: "./{{ test_path }}/test_results.cfg"
    when: "template_status is failed"

  - name: "{{ feature | upper }}: {{ test_name | upper }}-> SHOW THE DIFF"
    debug:
      var: "diff.diff_output"

  - name: "{{ feature | upper }}: {{ test_name | upper }}-> ASSERT THAT THERE IS NO DIFF"
    assert:
      that: 
        - "diff.diff_output == ''"
    ignore_errors: true
    register: "assert_result"

  - name: "{{ feature | upper }}: {{ test_name | upper }}-> GENERATE TEST LOG"
    template:
      src: "report.j2"
      dest: "{{ output_dir }}/reports/{{ feature }}_{{ test_name }}.txt"
